from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class IntentSpec:
    name: str
    family: str
    description: str
    synonyms: list[str]
    tool: str
    model: str
    operation: str  # search_read | group | aggregate
    measure_field: str | None = None
    groupby: list[str] = field(default_factory=list)
    orderby: str = ""
    limit_default: int = 1
    domain_template: list[list[Any]] = field(default_factory=list)
    default_fields: list[str] = field(default_factory=list)


INTENT_CATALOG: dict[str, IntentSpec] = {
    "list_ultimas_ventas_con_factura": IntentSpec(
        name="list_ultimas_ventas_con_factura",
        family="ventas",
        description="Últimas ventas que tienen factura asociada",
        synonyms=[
            "ultimas ventas con factura",
            "últimas ventas con factura",
            "ultimas ventas con facturas",
            "últimas ventas con facturas",
            "ultimas ventas que tengan factura",
            "últimas ventas que tengan factura",
            "ultimas ventas que tengan facturas",
            "últimas ventas que tengan facturas",
            "dime las ultimas ventas que tengan facturas",
            "dime las últimas ventas que tengan facturas",
        ],
        tool="query_odoo_search",
        model="sale.order",
        operation="search_read",
        orderby="date_order desc",
        limit_default=5,
        default_fields=["name", "partner_id", "date_order", "amount_total", "state"],
        domain_template=[
            ["state", "in", ["sale", "done"]],
            ["invoice_status", "!=", "no"],
        ],
    ),
    "list_ultimas_compras_con_factura": IntentSpec(
        name="list_ultimas_compras_con_factura",
        family="compras",
        description="Últimas compras que tienen factura asociada",
        synonyms=[
            "ultimas compras con factura",
            "últimas compras con factura",
            "ultimas compras con facturas",
            "últimas compras con facturas",
            "ultimas compras que tengan factura",
            "últimas compras que tengan factura",
            "ultimas compras que tengan facturas",
            "últimas compras que tengan facturas",
            "dime las ultimas compras que tengan facturas",
            "dime las últimas compras que tengan facturas",
        ],
        tool="query_odoo_search",
        model="purchase.order",
        operation="search_read",
        orderby="date_order desc",
        limit_default=5,
        default_fields=["name", "partner_id", "date_order", "amount_total", "state"],
        domain_template=[
            ["state", "in", ["purchase", "done"]],
            ["invoice_status", "!=", "no"],
        ],
    ),
    "ultimos_clientes_creados": IntentSpec(
        name="ultimos_clientes_creados",
        family="clientes",
        description="Últimos clientes creados",
        synonyms=[
            "últimos clientes creados",
            "ultimos clientes creados",
            "clientes creados recientemente",
            "últimos 10 clientes",
            "ultimos 10 clientes",
        ],
        tool="query_odoo_search",
        model="res.partner",
        operation="search_read",
        orderby="create_date desc",
        limit_default=10,
        default_fields=["name", "create_date"],
        domain_template=[
            ["customer_rank", ">", 0],
            ["active", "=", True],
            ["parent_id", "=", False],
            ["name", "!=", False],
            ["name", "!=", "."],
        ],
    ),
    "top_vendedor_por_monto": IntentSpec(
        name="top_vendedor_por_monto",
        family="ventas",
        description="Vendedor con más ventas por monto",
        synonyms=[
            "vendedor con más ventas",
            "vendedor que más ventas hizo",
            "quién vendió más",
            "quien vendio mas",
        ],
        tool="query_odoo_group",
        model="sale.order",
        operation="group",
        measure_field="amount_total",
        groupby=["user_id"],
        orderby="amount_total desc",
        limit_default=10,
        domain_template=[
            ["date_order", ">=", "{date_start}"],
            ["date_order", "<=", "{date_end}"],
            ["user_id", "!=", False],
        ],
    ),
    "top_vendedor_por_pedidos": IntentSpec(
        name="top_vendedor_por_pedidos",
        family="ventas",
        description="Vendedor con más pedidos",
        synonyms=[
            "vendedor con más pedidos",
            "quién hizo más pedidos",
            "quien hizo mas pedidos",
            "quién tuvo más órdenes",
            "quien tuvo mas ordenes",
        ],
        tool="query_odoo_group",
        model="sale.order",
        operation="group",
        measure_field="__count",
        groupby=["user_id"],
        orderby="__count desc",
        limit_default=10,
        domain_template=[
            ["date_order", ">=", "{date_start}"],
            ["date_order", "<=", "{date_end}"],
            ["user_id", "!=", False],
        ],
    ),
    "top_cliente_por_monto": IntentSpec(
        name="top_cliente_por_monto",
        family="clientes",
        description="Cliente con mayor monto comprado",
        synonyms=[
            "cliente que más compró",
            "cliente que mas compro",
            "top cliente por monto",
            "cliente con mayor facturación",
            "cliente con mayor facturacion",
            "qué cliente compró más",
            "que cliente compro mas",
            "cliente con más compras",
            "cliente con mas compras",
            "top cliente",
            "mejor cliente",
            "cliente que mas facturo",
            "cliente que más facturó",
            "cliente que mas nos compro",
            "cliente que más nos compró",
            "cliente con mayor monto comprado",
        ],
        tool="query_odoo_group",
        model="sale.order",
        operation="group",
        measure_field="amount_total",
        groupby=["partner_id"],
        orderby="amount_total desc",
        limit_default=10,
        domain_template=[
            ["date_order", ">=", "{date_start}"],
            ["date_order", "<=", "{date_end}"],
            ["partner_id", "!=", False],
        ],
    ),
    "top_proveedor_por_compras": IntentSpec(
        name="top_proveedor_por_compras",
        family="compras",
        description="Proveedor con mayor monto comprado",
        synonyms=[
            "proveedor con más compras",
            "proveedor con mas compras",
            "top proveedor por compras",
            "qué proveedor tuvo más compras",
            "que proveedor tuvo mas compras",
            "proveedor que más compras hizo",
            "proveedor que mas compras hizo",
            "proveedor al que mas compramos",
            "proveedor al que más compramos",
            "que proveedor nos vendio mas",
            "qué proveedor nos vendió más",
            "proveedor con mayor monto comprado",
            "proveedor con mayor facturacion",
            "proveedor con mayor facturación",
            "a que proveedor le compramos mas",
            "a qué proveedor le compramos más",
            "proveedor principal",
        ],
        tool="query_odoo_group",
        model="purchase.order",
        operation="group",
        measure_field="amount_total",
        groupby=["partner_id"],
        orderby="amount_total desc",
        limit_default=10,
        domain_template=[
            ["date_approve", ">=", "{date_start}"],
            ["date_approve", "<", "{date_end_next}"],
            ["partner_id", "!=", False],
            ["state", "in", ["purchase", "done"]],
        ],
    ),
    "top_proveedor_por_unidades": IntentSpec(
        name="top_proveedor_por_unidades",
        family="compras",
        description="Proveedor con mayor cantidad comprada",
        synonyms=[
            "proveedor con más unidades",
            "proveedor con mas unidades",
            "proveedor con mayor cantidad",
            "proveedor que más unidades compré",
            "proveedor que mas unidades compre",
            "qué proveedor me vendió más unidades",
            "que proveedor me vendio mas unidades",
            "proveedor con más unidades vendidas",
            "proveedor con mas unidades vendidas",
            "proveedor con mas cantidad vendida",
            "proveedor con más cantidad vendida",
            "a que proveedor le compramos mas unidades",
            "a qué proveedor le compramos más unidades",
            "proveedor con mayor cantidad de productos",
            "proveedor con mayor volumen vendido",
            "proveedor con mas unidades compradas",
            "proveedor con más unidades compradas",
        ],
        tool="query_odoo_group",
        model="purchase.order.line",
        operation="group",
        measure_field="product_qty",
        groupby=["partner_id"],
        orderby="product_qty desc",
        limit_default=10,
        domain_template=[
            ["order_id.date_approve", ">=", "{date_start}"],
            ["order_id.date_approve", "<=", "{date_end}"],
            ["order_id.state", "in", ["purchase", "done"]],
            ["partner_id", "!=", False],
        ],
    ),
    "producto_mas_comprado": IntentSpec(
        name="producto_mas_comprado",
        family="productos",
        description="Producto más comprado por cantidad",
        synonyms=[
            "producto más comprado",
            "producto mas comprado",
            "producto con más compras",
            "producto con mas compras",
        ],
        tool="query_odoo_group",
        model="purchase.order.line",
        operation="group",
        measure_field="product_qty",
        groupby=["product_id"],
        orderby="product_qty desc",
        limit_default=10,
        domain_template=[
            ["order_id.date_approve", ">=", "{date_start}"],
            ["order_id.date_approve", "<=", "{date_end}"],
            ["order_id.state", "in", ["purchase", "done"]],
        ],
    ),
    "producto_mas_vendido_por_cantidad": IntentSpec(
        name="producto_mas_vendido_por_cantidad",
        family="productos",
        description="Producto más vendido por cantidad",
        synonyms=[
            "producto más vendido",
            "producto mas vendido",
            "producto más vendido por cantidad",
            "producto mas vendido por cantidad",
            "producto con más unidades vendidas",
            "producto con mas unidades vendidas",
            "qué producto se vendió más",
            "que producto se vendio mas",
            "qué producto salió más",
            "que producto salio mas",
            "producto con más salida",
            "producto con mas salida",
            "articulo mas vendido",
            "artículo más vendido",
            "que articulo se vendio mas",
            "qué artículo se vendió más",
            "que item se vendio mas",
            "qué item se vendió más",
            "que fue lo que mas se vendio",
            "qué fue lo que más se vendió",
            "que producto vendimos mas",
            "qué producto vendimos más",
        ],
        tool="query_odoo_group",
        model="sale.order.line",
        operation="group",
        measure_field="product_uom_qty",
        groupby=["product_id"],
        orderby="product_uom_qty desc",
        limit_default=10,
        domain_template=[
            ["order_id.date_order", ">=", "{date_start}"],
            ["order_id.date_order", "<=", "{date_end}"],
        ],
    ),
    "producto_mas_vendido_por_monto": IntentSpec(
        name="producto_mas_vendido_por_monto",
        family="productos",
        description="Producto con mayor monto vendido",
        synonyms=[
            "producto que generó más ventas",
            "producto que genero mas ventas",
            "producto con más ventas",
            "producto con mas ventas",
            "top producto por monto",
            "producto con mayor facturación",
            "producto con mayor facturacion",
            "qué producto generó más ventas",
            "que producto genero mas ventas",
            "qué producto facturó más",
            "que producto facturo mas",
            "producto con mas ventas por monto",
            "producto con más ventas por monto",
            "que producto dejo mas ingresos",
            "qué producto dejó más ingresos",
            "que producto genero mas dinero",
            "qué producto generó más dinero",
            "top producto por ventas",
            "producto con mayor monto vendido",
        ],
        tool="query_odoo_group",
        model="sale.order.line",
        operation="group",
        measure_field="price_total",
        groupby=["product_id"],
        orderby="price_total desc",
        limit_default=10,
        domain_template=[
            ["order_id.date_order", ">=", "{date_start}"],
            ["order_id.date_order", "<=", "{date_end}"],
        ],
    ),
    "promedio_ventas_por_cliente_periodo": IntentSpec(
        name="promedio_ventas_por_cliente_periodo",
        family="ventas",
        description="Promedio de ventas por cliente en un periodo",
        synonyms=[
            "promedio de ventas por cliente",
            "promedio ventas por cliente",
            "media de ventas por cliente",
            "promedio vendido por cliente",
            "promedio de facturacion por cliente",
            "promedio de facturación por cliente",
            "cual es el promedio de ventas por cliente",
            "cuál es el promedio de ventas por cliente",
            "promedio de compra por cliente",
            "cuanto compra en promedio cada cliente",
            "cuánto compra en promedio cada cliente",
            "venta promedio por cliente",
        ],
        tool="query_odoo_group",
        model="sale.order",
        operation="avg_group",
        measure_field="amount_total",
        groupby=["partner_id"],
        limit_default=1000,
        domain_template=[
            ["date_order", ">=", "{date_start}"],
            ["date_order", "<=", "{date_end}"],
            ["partner_id", "!=", False],
        ],
    ),
    "ventas_total_periodo": IntentSpec(
        name="ventas_total_periodo",
        family="ventas",
        description="Monto total vendido en un periodo",
        synonyms=[
            "total de ventas",
            "ventas totales",
            "facturación total",
            "facturacion total",
        ],
        tool="query_odoo_group",
        model="sale.order",
        operation="aggregate",
        measure_field="amount_total",
        limit_default=1,
        domain_template=[
            ["date_order", ">=", "{date_start}"],
            ["date_order", "<=", "{date_end}"],
        ],
    ),
    "count_clientes": IntentSpec(
        name="count_clientes",
        family="clientes",
        description="Cantidad de clientes",
        synonyms=[
            "cuántos clientes tengo",
            "cuantos clientes tengo",
            "cantidad de clientes",
            "numero de clientes",
            "número de clientes",
        ],
        tool="query_odoo_count",
        model="res.partner",
        operation="count",
        domain_template=[
            ["customer_rank", ">", 0],
            ["active", "=", True],
            ["parent_id", "=", False],
            ["name", "!=", False],
        ],
    ),
    "count_ordenes_venta_periodo": IntentSpec(
        name="count_ordenes_venta_periodo",
        family="ventas",
        description="Cantidad de órdenes de venta en un periodo",
        synonyms=[
            "cuántas órdenes de venta hay",
            "cuantas ordenes de venta hay",
            "cuántos pedidos de venta hay",
            "cuantos pedidos de venta hay",
            "cantidad de órdenes de venta",
            "cantidad de pedidos de venta",
            "cuantos pedidos hay",
            "cuántos pedidos hay",
            "numero de pedidos",
            "número de pedidos",
            "cuantas ordenes se registraron",
            "cuántas órdenes se registraron",
            "cantidad de pedidos",
            "total de ordenes",
            "total de órdenes",
        ],
        tool="query_odoo_count",
        model="sale.order",
        operation="count",
        domain_template=[
            ["date_order", ">=", "{date_start}"],
            ["date_order", "<=", "{date_end}"],
        ],
    ),
    "facturas_vencidas_count": IntentSpec(
        name="facturas_vencidas_count",
        family="facturacion",
        description="Cantidad de facturas vencidas pendientes de pago",
        synonyms=[
            "cuántas facturas vencidas tengo",
            "cuantas facturas vencidas tengo",
            "facturas vencidas",
            "facturas vencidas pendientes",
            "cuantas facturas atrasadas hay",
            "cuántas facturas atrasadas hay",
            "numero de facturas vencidas",
            "número de facturas vencidas",
            "cuantas facturas estan fuera de fecha",
            "cuántas facturas están fuera de fecha",
            "facturas pendientes vencidas",
            "cantidad de facturas atrasadas",
        ],
        tool="query_odoo_count",
        model="account.move",
        operation="count",
        domain_template=[
            ["move_type", "=", "out_invoice"],
            ["state", "=", "posted"],
            ["payment_state", "in", ["not_paid", "partial"]],
            ["invoice_date_due", "<", "{today}"],
        ],
    ),
    "list_facturas_pendientes": IntentSpec(
        name="list_facturas_pendientes",
        family="facturacion",
        description="Listado de facturas publicadas pendientes de pago",
        synonyms=[
            "muestrame las facturas publicadas pero no pagadas",
            "muéstrame las facturas publicadas pero no pagadas",
            "lista facturas pendientes",
            "mostrar facturas pendientes",
            "ver facturas pendientes",
            "facturas pendientes detalle",
            "dame las facturas pendientes",
        ],
        tool="query_odoo_search",
        model="account.move",
        operation="search_read",
        orderby="invoice_date desc",
        limit_default=20,
        default_fields=["name", "partner_id", "invoice_date", "amount_total", "payment_state", "state", "move_type"],
        domain_template=[
            ["move_type", "=", "out_invoice"],
            ["state", "=", "posted"],
            ["payment_state", "in", ["not_paid", "partial"]],
        ],
    ),
    "count_facturas_pendientes": IntentSpec(
        name="count_facturas_pendientes",
        family="facturacion",
        description="Cantidad de facturas pendientes de pago",
        synonyms=[
            "facturas pendientes",
            "cuántas facturas pendientes tengo",
            "cuantas facturas pendientes tengo",
            "facturas por pagar",
            "cuantas facturas no pagadas hay",
            "cuántas facturas no pagadas hay",
            "facturas por cobrar",
            "numero de facturas pendientes",
            "número de facturas pendientes",
            "cuantas facturas siguen abiertas",
            "cuántas facturas siguen abiertas",
            "cuantas facturas estan sin pagar",
            "cuántas facturas están sin pagar",
            "cantidad de facturas pendientes",
            "facturas pendientes de cobro",
        ],
        tool="query_odoo_count",
        model="account.move",
        operation="count",
        domain_template=[
            ["move_type", "=", "out_invoice"],
            ["state", "=", "posted"],
            ["payment_state", "in", ["not_paid", "partial"]],
        ],
    ),
    "list_facturas_emitidas_periodo": IntentSpec(
        name="list_facturas_emitidas_periodo",
        family="facturacion",
        description="Listado de facturas emitidas (publicadas) en un periodo",
        synonyms=[
            "que facturas se emitieron esta semana",
            "qué facturas se emitieron esta semana",
            "facturas emitidas esta semana",
            "lista de facturas emitidas",
            "muestrame las facturas emitidas",
            "muéstrame las facturas emitidas",
            "facturas publicadas del periodo",
        ],
        tool="query_odoo_search",
        model="account.move",
        operation="search_read",
        orderby="invoice_date desc",
        limit_default=20,
        default_fields=["name", "partner_id", "invoice_date", "amount_total", "payment_state", "state", "move_type"],
        domain_template=[
            ["move_type", "=", "out_invoice"],
            ["state", "=", "posted"],
            ["invoice_date", ">=", "{date_start}"],
            ["invoice_date", "<=", "{date_end}"],
        ],
    ),
    "count_productos_activos": IntentSpec(
        name="count_productos_activos",
        family="productos",
        description="Cantidad de productos activos",
        synonyms=[
            "cuantos productos activos hay",
            "cuántos productos activos hay",
            "numero de productos activos",
            "número de productos activos",
            "cantidad de productos activos",
            "cuantos productos tengo activos",
            "cuántos productos tengo activos",
            "cuantos articulos activos hay",
            "cuántos artículos activos hay",
            "total de productos activos",
            "cuantos items activos hay",
            "cuántos items activos hay",
        ],
        tool="query_odoo_count",
        model="product.product",
        operation="count",
        domain_template=[
            ["active", "=", True],
        ],
    ),
    "top_clientes_ventas_mes": IntentSpec(
        name="top_clientes_ventas_mes",
        family="clientes",
        description="Top clientes por ventas del mes",
        synonyms=[
            "top clientes por ventas",
            "top clientes por ventas este mes",
            "clientes con mas ventas este mes",
            "clientes con más ventas este mes",
            "5 clientes con mas ventas este mes",
            "5 clientes con más ventas este mes",
            "mis 5 clientes con mas ventas este mes",
            "mis 5 clientes con más ventas este mes",
        ],
        tool="query_odoo_group",
        model="sale.order",
        operation="group",
        measure_field="amount_total",
        groupby=["partner_id"],
        orderby="amount_total desc",
        limit_default=5,
        domain_template=[
            ["state", "in", ["sale", "done"]],
            ["date_order", ">=", "{date_start}"],
            ["date_order", "<", "{date_end_next}"],
            ["partner_id", "!=", False],
        ],
    ),
    "clientes_facturas_vencidas_ranking": IntentSpec(
        name="clientes_facturas_vencidas_ranking",
        family="facturacion",
        description="Ranking de clientes por cantidad de facturas vencidas",
        synonyms=[
            "clientes con mas facturas vencidas",
            "clientes con más facturas vencidas",
            "que clientes tienen mas facturas vencidas",
            "qué clientes tienen más facturas vencidas",
            "top clientes con facturas vencidas",
        ],
        tool="query_odoo_group",
        model="account.move",
        operation="group",
        measure_field="amount_residual",
        groupby=["partner_id"],
        orderby="__count desc",
        limit_default=10,
        domain_template=[
            ["move_type", "=", "out_invoice"],
            ["state", "=", "posted"],
            ["payment_state", "in", ["not_paid", "partial"]],
            ["invoice_date_due", "<", "{today}"],
            ["partner_id", "!=", False],
        ],
    ),
    "ordenes_compra_pendientes_recepcion": IntentSpec(
        name="ordenes_compra_pendientes_recepcion",
        family="compras",
        description="Órdenes de compra pendientes de recepción",
        synonyms=[
            "ordenes de compra pendientes de recepcion",
            "órdenes de compra pendientes de recepción",
            "compras pendientes de recepcion",
            "compras pendientes de recepción",
            "ordenes de compra por recibir",
            "órdenes de compra por recibir",
        ],
        tool="query_odoo_search",
        model="purchase.order",
        operation="search_read",
        orderby="date_order desc",
        limit_default=10,
        default_fields=["name", "partner_id", "date_order", "state", "receipt_status"],
        domain_template=[
            ["state", "in", ["purchase", "done"]],
            ["receipt_status", "not in", ["full", "2_received"]],
        ],
    ),
    "ordenes_venta_pendientes_facturar": IntentSpec(
        name="ordenes_venta_pendientes_facturar",
        family="ventas",
        description="Pedidos de venta pendientes de facturar",
        synonyms=[
            "pedidos de venta pendientes de facturar",
            "ordenes de venta pendientes de facturar",
            "órdenes de venta pendientes de facturar",
            "ventas pendientes de facturar",
        ],
        tool="query_odoo_search",
        model="sale.order",
        operation="search_read",
        orderby="date_order desc",
        limit_default=20,
        default_fields=["name", "partner_id", "date_order", "amount_total", "state", "invoice_status"],
        domain_template=[
            ["state", "in", ["sale", "done"]],
            ["invoice_status", "=", "to invoice"],
        ],
    ),
    "pickings_pendientes_validar_hoy": IntentSpec(
        name="pickings_pendientes_validar_hoy",
        family="inventario",
        description="Pickings pendientes de validar hoy",
        synonyms=[
            "pickings pendientes de validar hoy",
            "que pickings estan pendientes de validar hoy",
            "qué pickings están pendientes de validar hoy",
            "pickings por validar hoy",
        ],
        tool="query_odoo_search",
        model="stock.picking",
        operation="search_read",
        orderby="scheduled_date asc",
        limit_default=20,
        default_fields=["name", "partner_id", "state", "scheduled_date", "origin", "picking_type_id"],
        domain_template=[
            ["state", "in", ["assigned", "waiting", "partially_available"]],
            ["scheduled_date", ">=", "{today_start}"],
            ["scheduled_date", "<", "{tomorrow_start}"],
        ],
    ),
    "resumen_operativo_hoy": IntentSpec(
        name="resumen_operativo_hoy",
        family="general",
        description="Resumen operativo del día con métricas clave",
        synonyms=[
            "dame un resumen operativo de hoy",
            "resumen operativo de hoy",
            "resumen operativo hoy",
            "resumen del dia de hoy",
            "resumen del día de hoy",
        ],
        tool="summary_operativo_hoy",
        model="dashboard.operativo",
        operation="summary_operativo",
        limit_default=1,
        domain_template=[],
    ),
    "count_pickings_por_estado": IntentSpec(
        name="count_pickings_por_estado",
        family="inventario",
        description="Conteo de pickings por estado operativo",
        synonyms=[
            "cuantos pickings estan en espera disponible y hecho",
            "cuántos pickings están en espera disponible y hecho",
            "conteo de pickings en espera disponible y hecho",
            "pickings en espera disponible y hecho",
        ],
        tool="summary_pickings_por_estado",
        model="stock.picking",
        operation="summary_pickings_estado",
        limit_default=1,
        domain_template=[],
    ),
}
